### ISSUE TITLE
knife-vcloud installation with ChefDK

### ISSUE THREAD

**Issue by monkey1016** [astratto/knife-vcloud#15]
Hi

Recently I tried to install knife-vcloud with ChefDK 0.4.0.  Unfortunately, it ran into some conflicts with `winrm` versions.  I updated the `knife-vcloud.gemspec` with the following changes, but I'm not sure if that's the right thing to do:
```ruby
s.add_dependency "chef", ">= 0.10.0"
s.add_dependency "knife-windows", ">= 0"
s.add_dependency "vcloud-rest", "~> 1.3"
s.add_dependency "winrm", "~> 1.1"
```
For what it's worth, it installed correctly and I'm able to log in and list items within vCloud Director.

Thanks

**Comment by astratto** [comment]
@monkey1016 those dependencies can actually be relaxed.
Should be fixed now. Thanks.
