### ISSUE TITLE
Question about cloning...

### ISSUE THREAD

**Issue by tarak** [astratto/knife-vcloud#8]
Here's my scenario:

- The vDC is named test
- The catalog in that vDC has several vApp templates with single VM's running both basic installations of linux and windows hosts.

Now how do I clone VM's from the catalog's vApp templates into an existing vApp? Is that possible?

The README does not state if this is possible at all and I haven't the possibility of trial and error in the vCloud used. Thanx for answers in advance!!!

P.S.: Sorry for opening this issue. I didn't know where to ask...

**Comment by astratto** [comment]
@tarak I'm closing this. Feel free to reopen it.
